name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          pip install pip-tools
          pip-compile requirements/requirements.in
          pip install -r requirements/requirements.txt

      - name: Run Tests
        run: pytest --cov=app tests/

      - name: Start Flask Server
        run: |
          python main.py &  # Runs Flask in the background
          sleep 5  # Waits 5 seconds for the server to start

      - name: Run API Tests
        run: pytest tests/


  lint:
    name: Run Code Quality Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"

      - name: Install linters and formatters
        run: pip install flake8 black autopep8

      - name: Run Code Quality Tests
        run: python tests/code_quality_tests.py --fix
