name: Run Tests and Code Quality Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements/requirements.txt
          pip install pytest pytest-cov ruff

      - name: Start Flask Server
        run: |
          python app/APIroutes.py &
          sleep 5

      - name: Run Tests with Coverage
        run: pytest --cov=. --cov-report=xml --cov-report=html

      - name: Check if coverage.xml exists
        run: ls -l coverage.xml

      - name: Ensure Coverage is at least 80%
        run: |
          coverage report --fail-under=80

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage.xml

      - name: Run Regression Tests
        run: pytest tests/test_reg.py --cov=. --cov-report=xml

      - name: Stop Flask Server
        run: pkill -f app/APIroutes.py || true

      - name: Run Code Quality Checks (Ruff)
        run: ruff check .
