name: CI - Run Tests & Linting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/requirements.txt

      - name: Run Linting with Flake8
        if: runner.os == 'Linux'
        run: |
          flake8 --max-line-length=88 --exclude=venv,__pycache__,.pytest_cache || true

      - name: Run Tests with Coverage
        run: pytest --cov=. --cov-report=xml --cov-report=term-missing

      - name: Upload Coverage Report
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml
          fail_ci_if_error: true
