name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pip-tools
          pip-compile requirements/requirements.in
          pip install -r requirements/requirements.txt

      - name: Run linting (flake8 & black)
        run: |
          ruff check --fix .

      - name: Remove previous coverage data
        run: coverage erase || true

      - name: Run tests with coverage
        run: |
          pytest --cov=models --cov=app \
                 --cov-report=term --cov-report=html
